{% set version = "0.1" %}

package:
  name: otmorris
  version: {{ version }}

source:
  fn: otmorris-{{ version }}.tar.gz  # [not win]
  url: https://github.com/openturns/otmorris/archive/v{{ version }}.tar.gz  # [not win]
  sha256: 385e7c9d73fc424b319679853a8d9a4e62a5553be634c46ec9faa70986e16242  # [not win]

  fn: otmorris-{{ version }}-py2.7-i686.exe  # [win32 and py27]
  url: https://github.com/openturns/build/releases/download/v1.8/otmorris-{{ version }}-py2.7-i686.exe  # [win32 and py27]
  sha256: 3998869d9f1673ad0af13795e17ed4ed0e3b0ae7249bc098b4ac373640d134fd  # [win32 and py27]

  fn: otmorris-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  url: https://github.com/openturns/build/releases/download/v1.8/otmorris-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  sha256: d57b08b10c3d83d08fb87541497054b0c72567beb46a1e3baaaa7fe45bbfbb7f  # [win64 and py27]

  fn: otmorris-{{ version }}-py3.4-i686.exe  # [win32 and py34]
  url: https://github.com/openturns/build/releases/download/v1.8/otmorris-{{ version }}-py3.4-i686.exe  # [win32 and py34]
  sha256: e8737b946b17abcea8b795603fce7d76995df8a44c9247737774ad0a18e9fddd  # [win32 and py34]

  fn: otmorris-{{ version }}-py3.4-x86_64.exe  # [win64 and py34]
  url: https://github.com/openturns/build/releases/download/v1.8/otmorris-{{ version }}-py3.4-x86_64.exe  # [win64 and py34]
  sha256: 0aa4ee6392f6e12f93ba2e9b63d273f07e8bd084c3566b36ad355bdf971feaaf  # [win64 and py34]

  fn: otmorris-{{ version }}-py3.5-i686.exe  # [win32 and py35]
  url: https://github.com/openturns/build/releases/download/v1.8/otmorris-{{ version }}-py3.5-i686.exe  # [win32 and py35]
  sha256: 145ca77604e77674c4a1ea0a302a62cf3cc219ea5918e3229e36c72f2bac44a6  # [win32 and py35]

  fn: otmorris-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  url: https://github.com/openturns/build/releases/download/v1.8/otmorris-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  sha256: 0632900125169bbac08fbed866821f68246f5ea79d5001040b21bda994b8ab65  # [win64 and py35]

  patches:
    # https://github.com/openturns/otmorris/pull/9
    - 0001-Take-interval-into-account-in-MorrisExperimentGrid.patch  # [unix]

build:
  number: 3

requirements:
  build:
    - toolchain
    - python
    - cmake  # [not win]
    - swig  # [not win]
    - openturns  # [not win]

  run:
    - python
    - openturns

test:
  imports:
    - otmorris

about:
  home: http://openturns.org/
  license: LGPLv3
  license_file: COPYING.LESSER  # [not win]
  summary: Morris screening module

extra:
  recipe-maintainers:
    - jschueller
