# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "NTgYeYsMavqi+fOg5CSGy9xG0B8+NkeIO7JEkd5EKYK0qglXroChGDmyfCdPcpotg29kecHt/g3wlYx/vc88D+9u6mkM5WtXdZhMNgC8uh2oPfE8qNw+znsYog5BYXhT3AKIKAQuxdCioHzuu98vdtVyk2eS+yJocr5BKXPDmGkt45kdaHWXrhQqXxjTC/25TTfmNy+I9FHaq5pNeW6QSc5yyB7E+Yjgi8/ZrNqo5LYcUZpAb5He/66NLEFIEXHVgIqwCQgsdhk3ZcDVhWe9JbuDm+lxiyDCOVFfbcRplK96Y6VW7VGXoVDPn96mfgmWTpy9ejGUT4+1V5GuXFkccilquAmJX7xc0zey++stlVcrc14CTMRS+VBngj5E0plAq/dMvqVZTt6iLgE9uUNa3Mtb9hydtr8SRmgrlJ1HA+KWAkjdm1ezlbY+R2T9HTs2YqPIb9jaJupHMv4614i4lhf9TSSgkTaxwPhwy9k1N4CPbMvkRW6354QbDFPUnEmwTFy/k46lAyAQgCpNQ01VwQ8c5fcTh6zkwASCoN7L8xXDXXo3qdd99R8sx+DOWC93NcL2YhO/SZTfAnZHu5s+wU8SDikoapCB5QQc/neryzxwu+DRuv6Dzeof1AP0t3B9g8h34BcAeDPFQFZsbljCs0CpzmanYGI8uwSLde/pWzk="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
