travis:
  secure:
    BINSTAR_TOKEN: RqyXZmMquAVk5Dlzoq8H6HFLjsm3yLCbmbIIdLikJd9QivWRBsrZtbm4jMFki38+JOt5vtFRQDNXmuPxQ6/2J4mYGTP8mHs8HOAihMvIbWzDoa6cKlJBJnbtPU/MEHuFvsuWTUKW7LzCgrSRxaeeHR48BC7Uy5vei+7lOXCikpctqSwdDu4FYpAFVQnQaheutWteP8Vy2mmmG3afS+rkdY0eaiXS6kShc64Dd1djzUww+p9IeKQTKu0S4tbTrstwMwdtpzW09zmXBlM9Bl1P8buJaKkAvyhUOl5gAZ8XJHaVQSnL4xkgTMpVa/VOqkiaHJvwExuhmLGpUTPUrn12Db7lBcP1BItZC6teSoYnUC3FqsKLWWBh3dVg+cgFmU6taM18GHN8r2CEno9CUXaiMC7V+bFqN8U24fUlYFOh7w92rI7eBRAbAa7Z38SyS9CVmtvNdnaaWdxfCjPlIlU4TiRjaGUcf8nFU8HnoS8BX6NehK5rx1ImI6TRgDQHv9kfazR3cPzTXImKAoYTF9VO/OmIIkP/4SsInEJYKipe+sE6lmtvPwp2rJBFIkmYQCmW7vijn0Z5Hh2fP8YN8KYRDZcpqFy5xEkTFH59avI5tzWKeN4l0wxaAzwfvJS/HoaqVU3tQQcQlAoMrVQjYYWHOnNtHYy18D8ec9Bpp2ieh/Y=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
